### ISSUE TITLE
Lab 2 (Detailed instructions - 2.2 - 11ii) - Incorrect "RequestCount"

### ISSUE THREAD

**Issue by rodrigotolledo** [aws-samples/amazon-ecs-catsndogs-workshop#16]
_Enter: Add 20 tasks when 2000 <= RequestCount < **000**_

I believe **000** should be **4000** instead.

**Comment by MitchyBAwesome** [comment]
Thanks for flagging this @rodrigotolledo. I've fixed the typo and merged. Closing this issue.
