### ISSUE TITLE
6.2 - Step 12 - Missing environment variable values

### ISSUE THREAD

**Issue by benphunter** [aws-samples/amazon-ecs-catsndogs-workshop#26]
The step asks you to create the following environment variables but shows the values as blank:
AWS_DEFAULT_REGION:
AWS_ACCOUNT_ID:

Should be:
AWS_DEFAULT_REGION: for example: eu-west-1
AWS_ACCOUNT_ID: for example: 12345567891011

**Comment by MitchyBAwesome** [comment]
Fixed. Merge pull request #32 from MitchyBAwesome/master
